# Menus
menu:
  Home: .
  Archives: archives/
  # Categories: categories
  # Tags: tags
  # About: https://narr.github.io/narr/

# Customize
customize:
  logo:
    enabled: true
    width: 40
    height: 40
    url: images/logo.png
  profile:
    enabled: true # Whether to show profile bar
    avatar: css/images/avatar.png
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: Jason Seonhong Kim
    author_title: Front End Developer
    location: https://twitter.com/nardgu
    follow: https://narr.github.io/narr/
  highlight: monokai
  sidebar: right # sidebar position, options: left, right
  thumbnail: false # enable posts thumbnail, options: true, false
  favicon: css/images/favicon.ico # path to favicon
  social_links:
    github: https://github.com/narr
    linkedin: https://www.linkedin.com/in/narrkim
    twitter: https://twitter.com/nardgu
    # facebook: /
    # dribbble: /
    rss: /atom.xml

# Widgets
widgets:
  - recent_posts
  # - category
  - archive
  - tag
  # - tagcloud
  # - links

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
  disqus: narr # enter disqus shortname here
  duoshuo: # enter duoshuo shortname here
  youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
  fancybox: true # options: true, false
  google_analytics: UA-69400538-7 # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
  links:
    Hexo: http://hexo.io
